<a href="https://colab.research.google.com/github/sagyant/sample_codes/blob/main/Array_Problems_Bilei.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# importing necessary libraries

import numpy as np
from random import randint, choice
from itertools import combinations, combinations_with_replacement

In [ ]:
# creating the necessary random 1-D arrays with 10 elements to be tested
test_array = np.random.choice(range(1,100), size=10, replace=False) 

In [ ]:
# Function to return tru or false based on the existence of a increasing triplet 
# but I am SURE it is not working the way i expected. Does not look efficient.
def increasing_triplet_sequence(arr):

  res = False
  a, b = arr[0], arr[1]
  for i in range(len(arr)-2):
    if a > b:
      a = arr[i+1]
      b = arr[i+2]
    elif arr[i+1] < arr[i+2]:
      res = True
      break
    else:
      a = b
      try:
       b = arr[i+3]
      except:
        res = False
  return(res, a, b, arr[i+2])

In [ ]:
# for i in range(10):
#   test_array = np.random.choice(range(1,100), size=10, replace=False)
#   print('array used as input :', test_array)
#   print(increasing_triplet_sequence(test_array))

In [ ]:
# Lets try some different approach, Lets start small
test_array = np.random.choice(range(1,20), size=8, replace=False)
# for i, num in enumerate(test_array.sort()):
#   print(i, num)

In [ ]:
print(test_array)
test1 = np.sort(test_array)
print(test1)
# [14 18  6  4 15  5  8  3]

[14 18  6  4 15  5  8  3]
[ 3  4  5  6  8 14 15 18]


In [ ]:
test = [14, 18,  6,  4, 15,  5,  8,  3]

In [ ]:
# Function for finding the eligible sequences.

def find_seq(arr):
  sequence_found = []
  for sequence in combinations(arr,3):
    # Use any of the ways to check if the list is sorted:
    # if sequence[0] < sequence[1] and sequence[1] < sets[2]:  #1
    if list(sorted(sequence)) == list(sequence):  #2
      sequence_found.append(sequence)
    else:
      continue
  return sequence_found

# This solution is working fine. Let's try one more approach
for i in range(20):
  random_array = np.random.choice(range(1,20), size=8, replace=False)
  print(random_array, '\n', find_seq(random_array))

In [4]:
# trying Sweta's Approach. This is also working fine.

def check_lesser_bigger(arr):
  out_list = []
  for i in range(1, len(arr)-1):
    for j in range(i):
      if arr[j] < arr[i]:
        for k in range(i+1,len(arr)):
          if arr[k] > arr[i]:
            out_list.append([arr[j], arr[i], arr[k]])
  return out_list


# This solution is also implemented fine. 

for i in range(20):
  random_array = np.random.choice(range(1,20), size=8, replace=False)
  print(random_array, '\n', check_lesser_bigger(random_array))

In [5]:
test = np.array([12, 11, 10,5,6, 2, 30])

In [6]:
check_lesser_bigger(test)

[[5, 6, 30]]